spring.application.name=dailymotionminer
server.port=8081

logging.level.aiss.dailymotionminer.controller=DEBUG

# La API de Dailymotion suele colgar de api.dailymotion.com
dailymotionminer.baseuri=https://api.dailymotion.com
dailymotionminer.maxVideos=10
dailymotionminer.maxPages=2

videominer.uri=http://localhost:8080/videominer/channels