spring.application.name=dailymotionminer
server.port=8081
logging.level.aiss.dailymotionminer.controller=DEBUG
dailymotionminer.baseuri=https://api.dailymotion.com
dailymotionminer.maxVideos=10
dailymotionminer.maxPages=2
videominer.uri=http://localhost:8080/videominer/channels
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.override-with-generic-response=false
