spring.application.name=peertubeminer
server.port=8082

logging.level.com.aiss.PeerTubeMiner.controller=DEBUG

peertubeminer.baseuri=https://peertube2.cpy.re/api/v1
peertubeminer.maxVideos=10
peertubeminer.maxComments=2

videominer.uri=http://localhost:8080/videominer/channels